# This workflow will build and deploy a React application to an Azure Web App
# when a commit is pushed to your default branch.

name: Deploy to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: excel-viewer-app        # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'build'        # set this to the path to your build output folder
  NODE_VERSION: '18.x'                      # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build React app
      run: npm run build
      env:
        NODE_ENV: production
        GENERATE_SOURCEMAP: false

    - name: Run tests (optional)
      run: npm test -- --watchAll=false --coverage --passWithNoTests
      continue-on-error: true

    - name: Upload build artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: react-app
        path: build/
        retention-days: 1

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: react-app
        path: build/

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Display deployment URL
      run: |
        echo "🎉 App deployed successfully!"
        echo "🌐 URL: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"